name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          failOnError: true
          commitMode: true
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<h3>Statistics</h3>\n\n- <b>Number of commits</b>: #{{COMMITS}}\n- <b>Number of changed files</b>: #{{CHANGED_FILES}}\n- <b>Added lines</b>: #{{ADDITIONS}}\n- <b>Deleted lines</b>: #{{DELETIONS}}",
              "pr_template": "#{{TITLE}} (#{{MERGE_SHA}})",
              "base_branches": ["main"],
              "tag_resolver": {
                "method": "sort"
              },
              "categories": [
                {
                    "title": "## ðŸ¦¾ Features",
                    "labels": ["feat"]
                },
                {
                    "title": "## ðŸ› Fixes",
                    "labels": ["fix"]
                },
                {
                    "title": "## ðŸš€ Performance",
                    "labels": ["perf"]
                },
                {
                    "title": "## ðŸ“˜ Documentation",
                    "labels": ["docs"]
                },
                {
                    "title": "## ðŸ—ï¸ Refactorings",
                    "labels": ["refactor"]
                },
                {
                    "title": "## ðŸ¤– CI",
                    "labels": ["ci"]
                },
                {
                    "title": "## âš’ï¸ Build",
                    "labels": ["build"]
                },
                {
                    "title": "## â±ï¸ Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## ðŸŽ¨ Style",
                    "labels": ["style"]
                },
                {
                    "title": "## ðŸ§¹ Chore",
                    "labels": ["chore"]
                },
                {
                    "title": "## â†©ï¸ Reverted",
                    "labels": ["revert"]
                },
                {
                    "title": "## â” Uncategorized",
                    "labels": []
                }
              ],
              "label_extractor": [
                {
                    "pattern": "(.+):(.+)",
                    "target": "$1",
                    "on_property": "title"
                }
              ],
              "transformers": [
                {
                  "pattern": "(.+):(.+)",
                  "target": "-$2"
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: true

      - name: Set up environment variables
        id: vars
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "VERSION=$TAG_NAME" >> $GITHUB_ENV
          echo "RELEASE_NAME=SaSHa-$TAG_NAME" >> $GITHUB_ENV
          mkdir -p ./bin

      - name: Build for Linux x64
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-X 'main.version=${{ env.VERSION }}'" -o ./bin/sasha-linux-amd64

      - name: Build for Linux ARM64
        run: |
          GOOS=linux GOARCH=arm64 go build -ldflags="-X 'main.version=${{ env.VERSION }}'" -o ./bin/sasha-linux-arm64

      - name: Build for macOS Intel
        run: |
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X 'main.version=${{ env.VERSION }}'" -o ./bin/sasha-darwin-amd64

      - name: Build for macOS ARM (Apple Silicon)
        run: |
          GOOS=darwin GOARCH=arm64 go build -ldflags="-X 'main.version=${{ env.VERSION }}'" -o ./bin/sasha-darwin-arm64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: ./bin/*
          if-no-files-found: error

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "SaSHa ${{ env.VERSION }}"
          body: ${{ steps.github_release.outputs.changelog }}
          files: |
            ./bin/sasha-linux-amd64
            ./bin/sasha-linux-arm64
            ./bin/sasha-darwin-amd64
            ./bin/sasha-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}